{"timestamp":"2025-07-11T23:48:15.804356","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-11T23:48:15.806095","level":"info","event":"Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-11T23:48:15.898606Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T23:48:15.898773Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T23:48:15.898859Z","level":"info","event":"Current task name:transform_load_weather_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T23:48:15.898965Z","level":"info","event":"Dag name:weathermap_api","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T23:48:15.906258","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"PermissionError","exc_value":"[Errno 13] Permission denied: 'current_weather_data_portland_20250711234815.csv'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/ubuntu/airflow/dags/weather_dag.py","lineno":49,"name":"transform_load_data"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/util/_decorators.py","lineno":333,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py","lineno":3986,"name":"to_csv"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/format.py","lineno":1014,"name":"to_csv"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py","lineno":251,"name":"save"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py","lineno":873,"name":"get_handle"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-11T23:48:15.909266Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T23:48:15.909397Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T23:48:15.909477Z","level":"info","event":"Task:<Task(PythonOperator): transform_load_weather_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T23:48:15.909548Z","level":"info","event":"Failure caused by [Errno 13] Permission denied: 'current_weather_data_portland_20250711234815.csv'","chan":"stdout","logger":"task"}
